# Generated by Django 2.0.3 on 2018-06-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=400)),
                ('Address', models.CharField(max_length=400)),
                ('Mobile', models.CharField(max_length=200)),
                ('Model', models.CharField(max_length=400)),
                ('Price', models.CharField(max_length=400)),
                ('Discount', models.CharField(max_length=200)),
                ('Gst', models.CharField(max_length=400)),
            ],
        ),
    ]
